name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - run: |
          npm install -g markdownlint-cli
          pip3 install jsonschema-cli
      - run: task
